# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Songyi Lee
title: 
email: happypine37@gmail.com
# email_title: Email (Email title override)
title:
phone: +82) 010-4494-2646
# phone_title: Phone (Phone title override)


# Dark Mode (true/false/never)
darkmode: false

# Additional icon links

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/증명사진.jpg
about_content: | # this will include new lines to allow paragraphs

content: 
  - title: EDUCATION
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [2020.09 ~ present]   **M.S. degree expected in computer science and engineering, Dongguk University, Seoul, Korea**
      - [2013.03 ~ 2017.02]   **B.A. Major in Agricultural Economics, Minor in Computer Science and engineering, Chungnam National University, Daejeon, Korea**
      - [2009.03 ~ 2012.02]   **Asuncion High School**, Paraguay

  - title: RESEARCH
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [2022.03]  **Songyi Lee, "Automatic Stock Trading based on Deep Reinforcement Learning using XAI(Explainable AI)"**, ARTINTEL2022 (Artificial Intelligence, Machine Learning and Data Science World Conference).
      - [2021.05]  **Songyi Lee, Bongkyo Moon, Juntae Kim, "Malware Classification Schemes Based on CNN Using Images and Metadata"**, 2021 Korea Information Processing Society Conference.
      - [2015.07]  **Songyi Lee, Yeon-a Park, "Proposed Expansion of Agricultural Product Consumption Using Omni-Channel" (Awarded)**, 	KAAFP(Korean Association of Agricultural and Food Policy), 25th KAAFP Conference.
      - [2014.07]  **Eunji Kim‧Yeji Song‧Songyi Lee‧Sujin Hwang, "Analysis of rice confectionery consumption and competitiveness improvement plan: Using STP strategy" (Awarded)**, KAAFP(Korean Association of Agricultural and Food Policy), 24th KAAFP Conference.
      
  - title: WORK
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [2020.01 ~ 2020.05]   **ARION Technology Inc. (UNIQUE LAB) / Designer, Marketing Strategy Division**
      - [2020.04 ~ 2020.12]   **DK EYEWEAR GROUP L.L.C / Designer, Business Planning Division**

  - title: EXPERIENCE
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [2021.04 ~ 2021.10]  **2021 National Cryptographic Technology Specialist Training Course**, Certificated
      - [2017.02]  **Data Storage Portable Scan Device**, Patent Pending (2017-0013776)
      
  - title: LANGUAGE
    layout: list
    content:
      - layout: left
        title: 
        sub_title: English
        caption: OPIC IH 
        quote: >
        description: | # this will include new lines to allow paragraphs
      - layout: left
        title: 
        sub_title: Spanish
        caption: DELE B2
        quote: >   
        description: | # this will include new lines to allow paragraphs
        
  - title: CERTIFICATE
    layout: list
    content:
      - layout: left
        title: 
        sub_title: Engineer Information Processing
        caption: 2016.07.15
        quote: >
        description: | # this will include new lines to allow paragraphs
      - layout: left
        title: 
        sub_title: Distribution Manager Level-Ⅱ
        caption: 2016.05.11
        quote: >   
        description: | # this will include new lines to allow paragraphs          

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
