# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Songyi Lee
title: 
email: happypine37@gmail.com
# email_title: Email (Email title override)
title:
phone: +82) 010-5114-3997
# phone_title: Phone (Phone title override)


# Dark Mode (true/false/never)
darkmode: false

# Additional icon links
additional_links:
- title: Youtube
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: https://youtu.be/169bmBmCO6E


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/증사_이송이.jpg
about_content: | # this will include new lines to allow paragraphs
  I am an **AI Engineer** at KyoboDTS, holding an **MSc in Computer Science and Engineering** from **Dongguk University, Seoul, Korea**.
  
  My expertise lies in **machine learning, deep learning, reinforcement learning, and explainable AI (XAI).**
  I am passionate about building practical AI solutions by combining state-of-the-art techniques with a deep understanding of user needs and business goals.
  
  I have hands-on experience in analyzing and modeling complex datasets across various domains, including **finance, cybersecurity** and **medical imaging**, with a particular focus on **financial time series analysis**.

  Key projects include:

  * Developed a robo-advisor solution for portfolio recommendation using Graph Neural Networks(GNN)
  
  * Built automated stock trading models using deep reinforcement learning(DRL)

  * Implemented CNN-based malware classifiers using image and metadata representations

  * Developed CNN-based classifiers for skin lesion image classification

  I am committed to building **interpretable, reliable, and user-centered AI systems**, and transforming advanced research into meaningful real-world applications.

content: 
  - title: EDUCATION
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [2020.09 ~ 2022.08]   **M.S.c in computer science & engineering, Dongguk University, Seoul, Korea**
      
        **Master's Thesis:** "A Study on the Optimization Method of Stock Trading Based on Deep Reinforcement Learning Using Explainable AI(XAI).", 2022.
      - [2013.03 ~ 2017.02]   **B.A. Major in Agricultural Economics, Minor in Computer Science & engineering, Chungnam National University, Daejeon, Korea**
      - [2009.03 ~ 2012.02]   **Asuncion High School**, Paraguay

  - title: RESEARCH
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [2022.03]  **Songyi Lee, Bongkyo Moon, "Automatic Stock Trading based on Deep Reinforcement Learning using XAI(Explainable AI)"**, ARTINTEL2022 (Artificial Intelligence, Machine Learning and Data Science World Conference).
      - [2021.05]  **Songyi Lee, Bongkyo Moon, Juntae Kim, "Malware Classification Schemes Based on CNN Using Images and Metadata"**, 2021 Korea Information Processing Society Conference.
      - [2015.07]  **Songyi Lee, Yeon-a Park, "Proposed Expansion of Agricultural Product Consumption Using Omni-Channel" (Awarded)**, 	KAAFP(Korean Association of Agricultural and Food Policy), 25th KAAFP Conference.
      - [2014.07]  **‧Songyi Lee, Yeji Song, Sujin Hwang, Eunji Kim, "Analysis of rice confectionery consumption and competitiveness improvement plan: Using STP strategy" (Awarded)**, KAAFP(Korean Association of Agricultural and Food Policy), 24th KAAFP Conference.
      
  - title: WORK
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [2022.11 ~ present]   **AI Engineer**, AI Business Team, **KYOBO DTS**
      - [2022.04 ~ 2022.09]   **Python Instructor**, After-school Program, **Wolgye Middle School**
      - [2019.12 ~ 2020.05]   **Designer**, Marketing Strategy Division, **ARION Technology Inc. (UNIQUE LAB)**
      - [2019.03 ~ 2019.12]   **Designer**, Local Sales Department, **DK EYEWEAR GROUP L.L.C**

  - title: EXPERIENCE
    layout: text
    content: | # this will include new lines to allow paragraphs
      - [2021.04 ~ 2021.10]  **National Cryptographic Technology Specialist Training Course 2021**, National Security Research Institute, Certificated
      - [2021.05 ~ 2021.09] **Financial Security Camp 2021**, Financial Security Institute, Certificated
      - [2017.02]  **Data Storage Portable Scan Device**, Patent Pending (No: 2017-0013776)

  - title: SKILL
    layout: text
    content: |
      - **Programming Languages**
        Python, Java, HTML, CSS

      - **Deep Learning & Data Science Frameworks**
        PyTorch, TensorFlow, Keras, OpenCV, Scikit-learn, Pandas, NumPy, Matplotlib, Seaborn  

      - **Database**
        MySQL, PostgreSQL

      - **Development Tools & MLOps**
        Git, Docker, Jupyter Notebook, VS Code, Eclipse 

      - **CI/CD**
        Jenkins

      - **Cloud Infrastructure**
        AWS EC2, S3, Lambda, RDS, CloudWatch

  # - title: SKILL
  #   layout: list
  #   content:
  #     - layout: text
  #       sub_title: Programming Languages
  #       caption: Python, JAVA
  #       quote: >
  #       description: |

  #     - layout: text
  #       sub_title: Deep Learning & Data Science Frameworks
  #       caption: PyTorch, TensorFlow, Keras, OpenCV, Scikit-learn, Pandas, Numpy, Matplotlib, Seaborn
  #       quote: >
  #       description: |

  #     - layout: text
  #       sub_title: Database
  #       caption: MySQL, PostgreSQL
  #       quote: >
  #       description: |  

  #     - layout: text
  #       sub_title: Development Tools & MLOps
  #       caption:  Git, Docker, Jupyter Notebook, VS Code, Eclipse
  #       quote: >
  #       description: |

  #     - layout: text
  #       sub_title: Cloud Infrastructure
  #       caption:  AWS EC2, S3, Lambda, RDS, CloudWatch
  #       quote: >
  #       description: |

  #     - layout: text
  #       sub_title: CI/CD
  #       caption:  Jenkins
  #       quote: >
  #       description: |
  
  - title: LANGUAGE
    layout: list
    content:
      - layout: left
        title: 
        sub_title: English
        caption: OPIC IH 
        quote: >
        description: | # this will include new lines to allow paragraphs
      - layout: left
        title: 
        sub_title: Spanish
        caption: DELE B2
        quote: >   
        description: | # this will include new lines to allow paragraphs

  - title: CERTIFICATE
    layout: list
    content:
      - layout: left
        title: 
        sub_title: Engineer Information Processing
        caption: 2016.07.15
        quote: >
        description: | # this will include new lines to allow paragraphs
      - layout: left
        title: 
        sub_title: Distribution Manager Level-Ⅱ
        caption: 2016.05.11
        quote: >   
        description: | # this will include new lines to allow paragraphs          

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
